FROM python:3.9

WORKDIR /code

COPY ./runner/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# COPY ./ /code/

# CMD [ "python", "utils/createTables.py"]
CMD [ "python", "runner/main.py"]